const EMOTES = [
['Standing Bow','Uncommon',''],['Touch Gloves','Uncommon','2Player'],
['61','Rare','Looping, Syncing, VFX'],['67','Rare','Looping, Syncing, VFX'],['Caged','Rare','Looping, Movable'],['Come On','Rare',''],['Concentration','Rare','VFX'],['Cookout','Rare','Looping'],['Demonic','Rare','Looping, VFX'],['Facepalm','Rare','Toxic'],['Flute','Rare','Looping, ForceMove, Syncing, VFX'],['Franky','Rare','VFX'],['Friday Night','Rare','Looping, ForceMove'],['Gangnam','Rare','Looping, Movable'],['Heart','Rare','Looping, VFX'],['Hit Me','Rare',''],['Inspect','Rare','Looping'],['Kabuki','Rare','Looping'],['Karaoke','Rare','Looping, VFX'],['Kickback','Rare','Looping'],['Laugh','Rare','Toxic'],['LeSalsa','Rare','Looping, Syncing'],['Liar','Rare','Looping, Syncing, VFX'],['Lookaway','Rare',''],['Muscle','Rare','Looping, ForceMove, VFX'],['One-Arm Pushup','Rare','Looping'],['Overdrive','Rare','Looping, Movable'],['PBJT','Rare','Looping'],['Penguin','Rare','Looping'],['Poke','Rare','Looping, Syncing'],['Raise Hand','Rare',''],['Salsa','Rare','Looping'],['Shadowboxing','Rare',''],['Shakedown','Rare','Looping'],['Sinister','Rare','Looping, Syncing, VFX'],['Slickback','Rare','Looping, ForceMove'],['Slide','Rare','Looping, ForceMove'],['Soldier of Dance','Rare','Looping, ForceMove'],['Sturdy','Rare','Looping, Movable'],['Sumo','Rare',''],['T-Pose','Rare','Looping, Movable'],['Take Your Time','Rare','Looping, Toxic'],['Tetoris','Rare','Looping, VFX'],['Threat','Rare',''],['Trigger','Rare','Looping, ForceMove'],['Warmup','Rare',''],['Wind Up','Rare',''],
['24-Hour Cinderella','Mythic','Looping, Syncing, VFX'],['Better Call','Mythic','Looping, Movable, VFX'],['Birthday Cake','Mythic','2Player, VFX'],['Clash','Mythic','2Player, VFX'],['Deadlift','Mythic','VFX'],['Death Note','Mythic','VFX, Toxic'],['Gear Second','Mythic','Looping, VFX'],['Geddan','Mythic','Movable'],['Gun-Trick-Sword','Mythic','VFX'],['Hakari','Mythic','VFX, Syncing, Toxic'],['Lagtrain','Mythic','Looping'],['Metsu','Mythic','VFX'],['Motivation Chair','Mythic','Looping, Movable'],['Necro','Mythic','Looping, VFX'],['Pearwell','Mythic','Looping, Movable, VFX'],['Power Up','Mythic','VFX, Syncing'],['Rock, Paper, Scissors','Mythic','2Player, VFX'],['Seahorse','Mythic','Looping, VFX'],['Sign','Mythic','Looping, Movable, Syncing, VFX'],['Take the L','Mythic','Toxic'],['Torture','Mythic','Looping, VFX'],['Trollolol','Mythic','Looping, ForceMove'],
['Calculation','Legendary','VFX, Perspective'],['Dragon','Legendary','VFX'],['Guitar','Legendary','Looping, VFX, Toxic'],['Phone Summon','Legendary','VFX, Perspective'],['Medal Selfie','Legendary','Looping, Movable, VFX, Perspective'],
['Vegetable','Limited','VFX'],['Virtual Insanity','Limited','Looping, Movable, VFX'],['Ultimate Apology','Limited','VFX'],['Whistle','Limited','Looping, VFX']
];

const refs = {
  '61':'61 meme','67':'67 meme','Caged':'Mortal Kombat 1 — Johnny Cage dance','Come On':'Devil May Cry — Nero taunt / Hajime no Ippo Wally panel','Concentration':'Devil May Cry — Vergil taunt','Cookout':'OluwaMark / cookout meme','Demonic':'Street Fighter — Akuma victory pose','Flute':'Kill Me Baby / Kyofuu All Back','Franky':'One Piece — Franky Super','Friday Night':'Yakuza — Friday Night Disco','Gangnam':'PSY — Gangnam Style','Heart':'Yakuza — Kiryu heart pose','Inspect':'Hajime no Ippo — Sawamura inspecting Ippo','Kabuki':'Kasane Teto at Cho-Kabuki','Karaoke':'Hajime no Ippo karaoke scene','Kickback':'Chainsaw Man opening','Laugh':'Team Fortress 2 — Schadenfreude','LeSalsa':'LeBron salsa meme','Liar':'Kasane Teto — Liar Dancer','Lookaway':'Hajime no Ippo — Aoki lookaway','Muscle':'Mashle workout','Overdrive':'Touhou — Overdrive','PBJT':'Peanut Butter Jelly Time','Penguin':'Club Penguin dance','Poke':'POKEDANCE','Salsa':'Mashle season 2 opening','Shakedown':'Watermelon dance meme','Sinister':'Rin Itoshi meme','Slickback':'Slickback / Jubi Slide','Slide':'Garou Slide','Soldier of Dance':'Team Fortress 2 — Kazotsky Kick','Sturdy':'Get Sturdy','T-Pose':'T-pose meme','Take Your Time':'Sonic idle animations','Tetoris':'Tetoris music video','Trigger':'Devil Trigger meme','Warmup':'Dragon Ball — Goku/Broly warmup','Wind Up':'Hajime no Ippo — Aoki arm-wrestling prep','24-Hour Cinderella':'Yakuza — 24-Hour Cinderella cinematic','Better Call':'Saul Goodman 3D meme','Birthday Cake':'2-player emote','Clash':'Mortal Kombat 1 clash intros','Death Note':'Death Note','Gear Second':'One Piece — Luffy Gear Second','Geddan':'Get Down / Geddan','Gun-Trick-Sword':'Devil May Cry — Dante style switch','Hakari':'Jujutsu Kaisen — Hakari dance','Lagtrain':'Inabakumori — Lagtrain','Metsu':'Street Fighter — Akuma Metsu','Motivation Chair':'Devil May Cry — Vergil lawn chair','Necro':'Touhou — Necromantic','Pearwell':'Pearto / Maxwell the Cat','Power Up':'Dragon Ball power-ups','Rock, Paper, Scissors':'2-player emote','Seahorse':'Spongebob — Patrick on a seahorse','Sign':'Shibamata Nigou','Take the L':'Fortnite — Take the L','Torture':'JoJo — Torture Dance','Trollolol':'Trollface / U MAD?','Calculation':'Jujutsu Kaisen — 530,000 IQ','Dragon':'Yakuza — shirt rip','Guitar':'Random acoustic tracks','Phone Summon':'Yakuza — Poundmate summons','Medal Selfie':'Medal collaboration emote','Vegetable':'Cartoon Beatbox Battles','Virtual Insanity':'Jamiroquai — Virtual Insanity','Ultimate Apology':'Extreme Japanese Apology meme','Whistle':'Ashita no Joe — Joe whistle'};

function rarityClass(r){return r.toLowerCase().replace(/[^a-z]/g,'')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function card([name, rarity, properties]){
  const tags=properties?properties.split(', ').map(x=>`<span class="emote-tag">${esc(x)}</span>`).join(''):'<span class="emote-tag">No special property listed</span>';
  const reference=refs[name]||'No reference listed';
  return `<article class="emote-card" data-name="${esc(name.toLowerCase())}" data-rarity="${rarity}">
    <div class="emote-preview"><div class="emote-placeholder"><b>GIF</b><span>Preview coming soon</span></div></div>
    <div class="emote-body"><div class="emote-top"><h3 class="emote-name">${esc(name)}</h3><span class="emote-rarity ${rarityClass(rarity)}">${esc(rarity)}</span></div><div class="emote-tags">${tags}</div><details><summary>Reference / notes</summary><div class="emote-detail">${esc(reference)}${name==='Sinister'?'<br><strong>Audio:</strong> currently listed as broken on the source wiki.':''}</div></details></div>
  </article>`;
}

function renderEmotes(){
 const root=document.getElementById('emoteSections'); if(!root)return;
 const q=(document.getElementById('emoteSearch')?.value||'').trim().toLowerCase();
 const filter=document.querySelector('.emote-filter.active')?.dataset.filter||'All';
 const groups=['Uncommon','Rare','Mythic','Legendary','Limited'];
 root.innerHTML=''; let visible=0;
 groups.forEach(r=>{const list=EMOTES.filter(e=>e[1]===r && (!q || e[0].toLowerCase().includes(q) || (refs[e[0]]||'').toLowerCase().includes(q)) && (filter==='All'||filter===r)); if(!list.length)return; visible+=list.length; const s=document.createElement('section');s.className='emote-section';s.innerHTML=`<div class="emote-section-head"><div><span class="section-kicker">${r==='Limited'?'EVENT / LIMITED':'RARITY'}</span><h2>${r} Emotes</h2></div><span class="emote-count">${list.length} entries</span></div><div class="emote-grid">${list.map(card).join('')}</div>`;root.appendChild(s)});
 document.getElementById('emoteCount').textContent=`${visible} shown / ${EMOTES.length} total`;
 document.getElementById('emoteEmpty').hidden=visible!==0;
}

document.addEventListener('DOMContentLoaded',()=>{
 document.querySelectorAll('.emote-filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.emote-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderEmotes()}));
 document.getElementById('emoteSearch')?.addEventListener('input',renderEmotes);
 renderEmotes();
});
