"use strict";

/*
==========================================================
UNTITLED BOXING GAME
GLOVES DATABASE
==========================================================

Image paths point to assets/gloves/.
Inventory images are used for collection cards.
Showcase images are used on individual glove pages.
==========================================================
*/

const gloves = [
    /* STANDARD CRATES */
    { id:"pain", name:"Pain", category:"Standard Crates", rarity:"Crate", crate:"Pain Crate", obtainable:true, description:"A standard glove crate available in the shop.", obtain:"Pain Crate", image:"assets/gloves/standard/150px-Pain_crate_icon.png", showcase:"assets/gloves/standard/780px-Pain_crate_contents.png", featured:false },
    { id:"gems", name:"Gems", category:"Standard Crates", rarity:"Crate", crate:"Gems Crate", obtainable:true, description:"A standard glove crate containing cosmetic gloves.", obtain:"Gems Crate", image:"assets/gloves/standard/150px-Gems_crate_icon.png", showcase:"assets/gloves/standard/780px-Gems_crate_contents.png", featured:false },
    { id:"dragon", name:"Dragon", category:"Standard Crates", rarity:"Crate", crate:"Dragon Crate", obtainable:true, description:"A standard glove crate featuring dragon-themed cosmetics.", obtain:"Dragon Crate", image:"assets/gloves/standard/150px-Dragon_crate_icon.png", showcase:"assets/gloves/standard/780px-Dragon_crate_contents.png", featured:false },
    { id:"sci-fi", name:"Sci-Fi", category:"Standard Crates", rarity:"Crate", crate:"Sci-Fi Crate", obtainable:true, description:"A standard glove crate featuring futuristic cosmetics.", obtain:"Sci-Fi Crate", image:"assets/gloves/standard/150px-Sci-fi_crate_icon.png", showcase:"assets/gloves/standard/780px-Sci-fi_crate_contents.png", featured:false },
    { id:"anime", name:"Anime", category:"Standard Crates", rarity:"Crate", crate:"Anime Crate", obtainable:true, description:"A standard glove crate featuring anime-inspired cosmetics.", obtain:"Anime Crate", image:"assets/gloves/standard/150px-Anime_crate_icon.png", showcase:"assets/gloves/standard/780px-Anime_crate_contents.png", featured:false },

    /* HOLIDAY CRATES */
    { id:"halloween-2023", name:"Halloween 2023", category:"Holiday Crates", rarity:"Event", obtainable:false, description:"The Halloween 2023 event crate.", obtain:"Halloween 2023 event; currently unobtainable", image:"assets/gloves/holiday/150px-Halloween_2023_crate_icon.png", showcase:"assets/gloves/holiday/780px-Halloween_2023_crate_contents.png" },
    { id:"christmas-2023", name:"Christmas 2023", subtitle:"Holly Jolly", category:"Holiday Crates", rarity:"Event", obtainable:false, description:"The Holly Jolly Christmas 2023 event crate.", obtain:"Christmas 2023 event; currently unobtainable", image:"assets/gloves/holiday/150px-Christmas_2023_crate_icon.png", showcase:"assets/gloves/holiday/780px-Christmas_2023_crate_contents.png" },
    { id:"halloween-2024", name:"Halloween 2024", category:"Holiday Crates", rarity:"Event", obtainable:false, description:"The Halloween 2024 event crate.", obtain:"Halloween 2024 event; currently unobtainable", image:"assets/gloves/holiday/150px-Halloween_2024_crate_icon.png", showcase:"assets/gloves/holiday/780px-Halloween_2024_crate_contents.png" },
    { id:"christmas-2024", name:"Christmas 2024", subtitle:"Jolly", category:"Holiday Crates", rarity:"Event", obtainable:false, description:"The Jolly Christmas 2024 event crate.", obtain:"Christmas 2024 event; currently unobtainable", image:"assets/gloves/holiday/150px-Christmas_2024_crate_icon.png", showcase:"assets/gloves/holiday/780px-Christmas_2024_crate_contents.png", featured:true },
    { id:"valentines-2026", name:"Valentine's 2026", category:"Holiday Crates", rarity:"Event", obtainable:false, description:"The Valentine's Day 2026 event crate.", obtain:"Valentine's Day 2026 event; currently unobtainable", image:"assets/gloves/holiday/150px-Valentine's_2026_crate_icon.gif", showcase:"assets/gloves/holiday/780px-Valentine's_2026_crate_contents.png", featured:true },

    /* RANKED */
    { id:"torn-bronze", name:"Torn Bronze", category:"Ranked Gloves", rarity:"Uncommon", obtainable:false, rank:"Bronze 3", description:"A ranked reward awarded for reaching Bronze 3.", obtain:"Reach Bronze 3 in Ranked", tradable:false, image:"assets/gloves/ranked/150px-TB_Inventory.png", showcase:"assets/gloves/ranked/380px-TB_Showcase.png" },
    { id:"patched-silver", name:"Patched Silver", category:"Ranked Gloves", rarity:"Rare", obtainable:false, rank:"Silver 3", description:"A ranked reward awarded for reaching Silver 3.", obtain:"Reach Silver 3 in Ranked", tradable:false, image:"assets/gloves/ranked/150px-PS_Inventory.png", showcase:"assets/gloves/ranked/380px-PS_Showcase.png" },
    { id:"fused-gold", name:"Fused Gold", category:"Ranked Gloves", rarity:"Mythic", obtainable:false, rank:"Gold 3", description:"A ranked reward awarded for reaching Gold 3.", obtain:"Reach Gold 3 in Ranked", tradable:false, image:"assets/gloves/ranked/150px-FS_Inventory.png", showcase:"assets/gloves/ranked/380px-FS_Showcase.png" },
    { id:"ultra-diamond", name:"Ultra Diamond", category:"Ranked Gloves", rarity:"Legendary", obtainable:false, rank:"Diamond 3", description:"A ranked reward awarded for reaching Diamond 3.", obtain:"Reach Diamond 3 in Ranked", tradable:false, image:"assets/gloves/ranked/150px-UD_Inventory.png", showcase:"assets/gloves/ranked/380px-UD_Showcase.png" },
    { id:"champion", name:"Champion", category:"Ranked Gloves", rarity:"Legendary", obtainable:false, rank:"Champion 3", description:"The highest ranked glove reward.", obtain:"Reach Champion 3 in Ranked", tradable:false, image:"assets/gloves/ranked/148px-CHMP_Inventory.png", showcase:"assets/gloves/ranked/380px-CHMP_Showcase.png", featured:true },

    /* BEOWULF */
    { id:"beowulf", name:"Beowulf", category:"Event Gloves", series:"Beowulf Series", rarity:"Event", obtainable:false, description:"The original red Beowulf gloves, awarded during the Valentine's Day 2024 event.", obtain:"Valentine's Day 2024 event", tradable:true, image:"assets/gloves/beowulf/147px-Beowulf_Inventory.png", showcase:"assets/gloves/beowulf/380px-Beowulf_Showcase.png", featured:true },
    { id:"bluowulf", name:"Bluowulf", category:"Event Gloves", series:"Beowulf Series", rarity:"Event", obtainable:false, description:"A blue Beowulf variant awarded during the June 2025 two-year anniversary event.", obtain:"June 2025 2-year anniversary event", tradable:true, image:"assets/gloves/beowulf/145px-Bluowolf_Inventory.png", showcase:"assets/gloves/beowulf/Bluowolf_Showcase.png", featured:true },
    { id:"beowulf-reborn", name:"Beowulf Reborn", category:"Event Gloves", series:"Beowulf Series", rarity:"Event", obtainable:false, description:"A remodeled version of the original Beowulf gloves.", obtain:"3-year anniversary event", tradable:true, image:"assets/gloves/beowulf/149px-Beowulf_Reborn_Inventory.png", showcase:"assets/gloves/beowulf/380px-Beowulf_Reborn_Showcase.png" },
    { id:"pridewulf", name:"Pridewulf", category:"Event Gloves", series:"Beowulf Series", rarity:"Event", obtainable:false, description:"An RGB Beowulf variant that changes colour over time.", obtain:"3-year anniversary event", tradable:true, image:"assets/gloves/beowulf/145px-Pridewulf_Inventory.png", showcase:"assets/gloves/beowulf/Pridewulf_Showcase.gif", featured:true },
    { id:"voidwulf", name:"Voidwulf", category:"Event Gloves", series:"Beowulf Series", rarity:"Event", obtainable:false, description:"A purple Beowulf variant that is currently unobtainable and associated with the Void ARG.", obtain:"Currently unobtainable", tradable:false, image:"assets/gloves/beowulf/148px-Voidwulf_Inventory.png", showcase:"assets/gloves/beowulf/500px-Drowningsome_voidwulf_teaser.png", featured:true, wip:true },

    /* BALROG */
    { id:"balrog", name:"Balrog", category:"Event Gloves", series:"Balrog Evolutions", rarity:"Event", obtainable:false, description:"Awarded for getting 50 knockdowns during the June 2024 one-year anniversary event.", obtain:"June 2024 1-year anniversary event", tradable:true, image:"assets/gloves/balrog/150px-Balrog_Inventory_v2.png", showcase:"assets/gloves/balrog/380px-Balrog_Showcase.png", featured:true, mobileNote:"On mobile devices, Balrog can receive an orange glow because of Roblox mobile rendering." },
    { id:"balrog-breaker", name:"Balrog Breaker", category:"Event Gloves", series:"Balrog Evolutions", rarity:"Event", obtainable:false, description:"The purple Balrog evolution.", obtain:"Break 100 guards", tradable:true, image:"assets/gloves/balrog/Balrog_Breaker_Inventory.png", showcase:"assets/gloves/balrog/380px-Breaker_Showcase.png" },
    { id:"balrog-greed", name:"Balrog Greed", category:"Event Gloves", series:"Balrog Evolutions", rarity:"Event", obtainable:false, description:"The green Balrog evolution.", obtain:"Earn $59,999", tradable:true, image:"assets/gloves/balrog/Balrog_Greed_Inventory.png", showcase:"assets/gloves/balrog/380px-Greed_Showcase.png" },
    { id:"balrog-perfect", name:"Balrog Perfect", category:"Event Gloves", series:"Balrog Evolutions", rarity:"Event", obtainable:false, description:"The red Balrog evolution.", obtain:"Perform 500 perfect dodges", tradable:true, image:"assets/gloves/balrog/Balrog_Perfect_Inventory.png", showcase:"assets/gloves/balrog/380px-Perfect_Showcase.png" },
    { id:"balrog-triumph", name:"Balrog Triumph", category:"Event Gloves", series:"Balrog Evolutions", rarity:"Event", obtainable:false, description:"The orange Balrog evolution.", obtain:"Win 50 matches", tradable:true, image:"assets/gloves/balrog/Balrog_Triumph_Inventory.png", showcase:"assets/gloves/balrog/380px-Triumph_Showcase.png" },
    { id:"balrog-ultimate", name:"Balrog Ultimate", category:"Event Gloves", series:"Balrog Evolutions", rarity:"Event", obtainable:false, description:"The blue Balrog evolution.", obtain:"Land 100 ultimates", tradable:true, image:"assets/gloves/balrog/Balrog_Ultimate_Inventory.png", showcase:"assets/gloves/balrog/380px-Ultimate_Showcase.png" },

    /* OTHER EVENTS */
    { id:"gilgamesh", name:"Gilgamesh", category:"Event Gloves", rarity:"Event", obtainable:false, description:"A Christmas 2024 event glove that slowly changes colour.", obtain:"Christmas 2024 event", tradable:true, image:"assets/gloves/events/149px-Gilgamesh_Inventory.png", showcase:"assets/gloves/events/339px-Gilgamesh_Showcase.png", featured:true },
    { id:"bringus-beater", name:"Bringus Beater", category:"Event Gloves", rarity:"Event", obtainable:false, description:"A reward from the Coach Bringus event during Roblox's August 2024 The Games event.", obtain:"Coach Bringus event", tradable:true, image:"assets/gloves/events/145px-Bringus_Beater_Inventory.png", showcase:"assets/gloves/events/Bringus_Beater_Showcase.png" },
    { id:"bringus-destroyer", name:"Bringus Destroyer", category:"Event Gloves", rarity:"Event", obtainable:false, description:"Awarded for defeating the Coach Bringus boss during The Games event.", obtain:"Defeat Coach Bringus", tradable:true, image:"assets/gloves/events/Bringus_Destroyer_Inventory.png", showcase:"assets/gloves/events/Bringus_Destroyer_Showcase.png" },
    { id:"troll", name:"Troll", category:"Event Gloves", rarity:"Event", obtainable:false, description:"A glove associated with the April Fools 2024 event, including an unusual variant.", obtain:"April Fools 2024 event", tradable:true, image:"assets/gloves/events/148px-Troll_Inventory.png", showcase:"assets/gloves/events/Troll_Showcase.png", featured:true },
    { id:"whoopee-concussion", name:"Whoopee Concussion", category:"Event Gloves", rarity:"Event", obtainable:false, description:"A reward from the April Fools 2026 event. Its upgraded version has the Prankster effect and fart sound effects on hits.", obtain:"April Fools 2026 event", tradable:true, image:"assets/gloves/events/147px-WhoCon_Inventory.png", showcase:"assets/gloves/events/333px-WhoCon_Showcase.png", featured:true },
    { id:"discovered", name:"Discovered", category:"Event Gloves", rarity:"Event", obtainable:false, description:"Awarded during the Walmart Discovered Perks promotional event in November 2025.", obtain:"5 knockdowns during the Discovered Perks event", tradable:true, image:"assets/gloves/events/148px-Discovered_Inventory.png", showcase:"assets/gloves/events/Discovered_Showcase.gif", unusual:"Spark" },

    /* ORIGINAL / BETA */
    { id:"default", name:"Default", category:"Original / Beta", rarity:"Uncommon", obtainable:false, description:"The original blocky default gloves worn by new players.", obtain:"Original game", tradable:true, image:"assets/gloves/beta/150px-Default_Inventory.png", showcase:"assets/gloves/beta/380px-Default_Showcase.png" },
    { id:"yellow", name:"Yellow", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original colour variant from the old glove line.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/150px-Yellow_Inventory.png", showcase:"assets/gloves/beta/Yellow_Showcase.png" },
    { id:"green", name:"Green", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original colour variant from the old glove line.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/150px-Green_Inventory.png", showcase:"assets/gloves/beta/289px-Green_Showcase.png" },
    { id:"blue", name:"Blue", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original colour variant from the old glove line.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/150px-Blue_Inventory.png", showcase:"assets/gloves/beta/274px-Blue_Showcase.png" },
    { id:"magenta", name:"Magenta", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original colour variant from the old glove line.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/149px-Magenta_Inventory.png", showcase:"assets/gloves/beta/269px-Magenta_Showcase.png" },
    { id:"white", name:"White", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original colour variant from the old glove line.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/148px-White_Inventory.png", showcase:"assets/gloves/beta/290px-White_Showcase.png" },
    { id:"black", name:"Black", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original colour variant from the old glove line.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/150px-Black_Inventory.png", showcase:"assets/gloves/beta/282px-Black_Showcase.png" },
    { id:"sleek", name:"Sleek", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"One of the original gloves sold through the old glove shop.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/149px-Beta_Sleek_Inventory.png" },
    { id:"classic", name:"Classic", subtitle:"New Default", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"Originally known as New Default. It was later moved to the Pain crate.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/150px-Beta_New_Default_Inventory.png" },
    { id:"carbon", name:"Carbon", category:"Original / Beta", rarity:"Beta", obtainable:false, description:"An original beta glove that was not reintroduced during the shop rework.", obtain:"Trading", tradable:true, image:"assets/gloves/beta/144px-Beta_Carbon_Inventory.png", showcase:"assets/gloves/beta/380px-Beta_Carbon_Showcase.png", featured:true },

    /* STYLE */
    { id:"counter-mastery", name:"Counter Mastery", category:"Style Gloves", rarity:"Upcoming", obtainable:false, description:"A style-themed glove associated with Counter mastery. Style gloves are currently unobtainable.", obtain:"Upcoming style glove feature", tradable:false, image:"assets/gloves/style/400px-Feedbacker_counter_showcase.png", showcase:"assets/gloves/style/400px-Feedbacker_counter_showcase.png", wip:true },
    { id:"smash-mastery", name:"Smash Mastery", category:"Style Gloves", rarity:"Upcoming", obtainable:false, description:"A style-themed glove associated with Smash mastery. Style gloves are currently unobtainable.", obtain:"Upcoming style glove feature", tradable:false, image:"assets/gloves/style/400px-Knuckleblaster_smash_showcase.png", showcase:"assets/gloves/style/400px-Knuckleblaster_smash_showcase.png", wip:true }
];

window.UBG_GLOVES = gloves;
